### ISSUE TITLE
Does not work with helix

### ISSUE THREAD

**Issue by elenakrittik** [binhtran432k/ungrammar-language-features#85]
From helix's logs:

```log
2024-11-09T19:48:42.158 helix_term::application [WARN] Ignoring a client/registerCapability request because dynamic capability registration is not enabled. Please report this upstream to the language server
```

Not sure what that means.

Additionally, [this line](https://github.com/binhtran432k/ungrammar-language-features/blob/e863ebed779d2770457eb5f750f286ebde36d4ff/packages/ungrammar-languageserver/src/ungramServer.ts#L120) accesses `initializationOptions`, which [may be `undefined`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initializeParams), causing the server to fail unless the user specifies an empty config (as opposed to not defining the config at all).

**Comment by binhtddev** [comment]
Hi @elenakrittik, thank you for your report. I just have release new version [v0.0.5](https://www.npmjs.com/package/ungrammar-languageserver).

Feel free to reopen if the issue still exist!

**Comment by elenakrittik** [comment]
Appreciate the quick response! Everything works flawlessly now!
