### ISSUE TITLE
Support for CRLF line endings

### ISSUE THREAD

**Issue by elenakrittik** [binhtran432k/ungrammar-language-features#86]
Currently, the language server refuses to parse CRLF line endings. While it's simple to reformat the file to Unix-style line endings, it would be great if the default Windows experience was better.

**Comment by binhtran432k** [comment]
The current behavior is based on the original ungrammar behavior ([see this line](https://github.com/rust-analyzer/ungrammar/blob/53bc777c2400acea2ee576123c9232d50731563c/src/lexer.rs#L113)) and I don't know the purpose of it. Maybe the author of ungrammar @matklad can explain this.

**Comment by binhtddev** [comment]
Hey @elenakrittik, it seems that this is an explicit design decision base on https://github.com/rust-analyzer/ungrammar/issues/59#issuecomment-2468657655. I will close it as not planned for now.

**Comment by elenakrittik** [comment]
I see, thanks anyway! Is a PR to support CRLF endings something you would accept?  I'm thinking of implementing parsing CRLF endings, but still emit a warning and replace CRLF with LF when formatting

**Comment by binhtddev** [comment]
@elenakrittik, It is a good hack but it is not consistent between editors. You can actually replace CRLF with LF but you cannot make sure that the editor will set the file to LF.

If you want to make your file mark as LF in git, you can use `.gitattributes` like this:

https://github.com/rust-lang/rust-analyzer/blob/fc98e0657abf3ce07eed513e38274c89bbb2f8ad/.gitattributes#L1

It will mark files as LF when clone the repository in window

**Comment by elenakrittik** [comment]
Oh, right. Well, thanks in any case!
